CREATE DATABASE BAITHI
USE BAITHI

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4),
	TENKH VARCHAR(20),
	DIACHI VARCHAR(10),
	LOAIKH VARCHAR(12)
)

ALTER TABLE KHACHHANG ALTER COLUMN MAKH CHAR(4) NOT NULL
ALTER TABLE KHACHHANG ADD CONSTRAINT PK_KH PRIMARY KEY (MAKH)

CREATE TABLE LOAICAY
(
	MALC CHAR(4),
	TENLC VARCHAR(20),
	XUATXU VARCHAR(10),
	GIA MONEY
)

ALTER TABLE LOAICAY ALTER COLUMN MALC CHAR(4) NOT NULL
ALTER TABLE LOAICAY ADD CONSTRAINT PK_LC PRIMARY KEY (MALC)

CREATE TABLE HOADON
(
	SOHD INT,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	KHUYENMAI NUMERIC
)

ALTER TABLE HOADON ALTER COLUMN SOHD INT NOT NULL
ALTER TABLE HOADON ALTER COLUMN MAKH CHAR(4)
ALTER TABLE HOADON ADD CONSTRAINT PK_HD PRIMARY KEY (SOHD)
ALTER TABLE HOADON ADD CONSTRAINT FK_KH_HD FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

CREATE TABLE CTHD
(
	SOHD INT,
	MALC CHAR(4),
	SOLUONG INT
)

ALTER TABLE CTHD ALTER COLUMN SOHD INT NOT NULL
ALTER TABLE CTHD ALTER COLUMN MALC CHAR(4) NOT NULL
ALTER TABLE CTHD ADD CONSTRAINT FK_HD_CTHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTHD ADD CONSTRAINT FK_LC_CTHD FOREIGN KEY (MALC) REFERENCES LOAICAY(MALC)
ALTER TABLE CTHD ADD CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MALC)
 -- NHAP DU LIEU
 -- KHACHHANG
INSERT INTO KHACHHANG VALUES ('KH01 ','Liz Kim Cuong ','Ha Noi ','Vang lai ')
INSERT INTO KHACHHANG VALUES ('KH02 ','Ivone Dieu Linh ','Da Nang ','Thuong xuyen ')
INSERT INTO KHACHHANG VALUES ('KH03  ','Emma Nhat Khanh','TP.HCM ','Vang lai ')
-- LOAICAY
INSERT INTO LOAICAY VALUES ('LC01', ' Xuong rong tai tho ','Mexico  ',180.000 )
INSERT INTO LOAICAY VALUES ('LC02 ', 'Sen thach ngoc ','Anh ',300.000)
INSERT INTO LOAICAY VALUES ('LC03 ', 'Ba mau rau ','Nam Phi', 270.000)
-- HOADON
INSERT INTO HOADON VALUES ('00001','22/11/2017','KH01',5)
INSERT INTO HOADON VALUES ('00002','04/12/','KH03',5)
INSERT INTO HOADON VALUES ('00003','43020','KH02 ',10)
-- CTHD
INSERT INTO CTHD VALUES ('00001','LC01  ',1)
INSERT INTO CTHD VALUES ('00001  ','LC02 ',2)
INSERT INTO CTHD VALUES ('00003','LC03',5)

-- RBTV
ALTER TABLE LOAICAY ADD CONSTRAINT CK_LC_NCSX_G CHECK ((XUATXU = 'Anh' AND  GIA > 250.000) OR (XUATXU <> 'Anh'))
--RBTV
ALTER TABLE HOADON ADD CONSTRAINT CK_HD_CTHD_SL_KM CHECK (((SELECT SUM(SOLUONG) FROM CTHD WHERE CTHD.SOHD = HOADON.SOHD) >=5 AND KHUYENMAI = 10) OR ((SELECT SUM(SOLUONG) FROM CTHD WHERE CTHD.SOHD = HOADON.SOHD) < 5 AND KHUYENMAI < 10))

