CREATE DATABASE QLGV
USE QLGV

CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) NOT NULL,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)

CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) NOT NULL,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)

CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL
)

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
)

CREATE TABLE LOP
(
	MALOP CHAR(3) NOT NULL,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4)
)

CREATE TABLE HOCVIEN
(
	MAHV CHAR(5) NOT NULL,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3)
)

CREATE TABLE GIANGDAY
(
	MALOP CHAR(3) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	MAGV CHAR(3),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME
)

CREATE TABLE KETQUATHI
(
	MAHV CHAR(5) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	LANTHI TINYINT NOT NULL,
	NGTHI SMALLDATETIME,
	NGVL SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10)
)
--1.Tạo quan hệ và khai báo tất cả các ràng buộc khóa chính, khóa ngoại. Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.
ALTER TABLE HOCVIEN ADD CONSTRAINT PK_HV PRIMARY KEY (MAHV)
ALTER TABLE HOCVIEN ADD CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE KHOA ADD CONSTRAINT PK_K PRIMARY KEY (MAKHOA)
ALTER TABLE KHOA ADD CONSTRAINT FK_K_GV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE MONHOC ADD CONSTRAINT PK_MH PRIMARY KEY (MAMH)
ALTER TABLE MONHOC ADD CONSTRAINT FK_MH_K FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE DIEUKIEN ADD CONSTRAINT PK_DK PRIMARY KEY (MAMH,MAMH_TRUOC)
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIAOVIEN ADD CONSTRAINT PK_GV PRIMARY KEY (MAGV)
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GV FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE GIANGDAY ADD CONSTRAINT PK_GD PRIMARY KEY (MALOP,MAMH)
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_L FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
ALTER TABLE GIANGDAY ALTER COLUMN MAGV CHAR(4)
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KETQUATHI ADD CONSTRAINT PK_KQT PRIMARY KEY (MAHV,MAMH,LANTHI)
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KQT_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)
ALTER TABLE KETQUATHI ALTER COLUMN MAMH VARCHAR(10) NOT NULL
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KQT_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE LOP ADD CONSTRAINT PK_L PRIMARY KEY (MALOP)
ALTER TABLE LOP ADD CONSTRAINT FK_L_HV FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)
ALTER TABLE LOP ADD CONSTRAINT FK_L_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
--Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.
ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(20)
ALTER TABLE HOCVIEN ADD DIEMTB NUMERIC(4,2)
ALTER TABLE HOCVIEN ADD XEPLOAI VARCHAR(10)
--2.Mã học viên là một chuỗi 5 ký tự, 3 ký tự đầu là mã lớp, 2 ký tự cuối cùng là số thứ tự học viên trong lớp. VD: “K1101”
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_MAHV CHECK(MAHV LIKE '[A-Z][0-9][0-9][0-9][0-9]')
ALTER TABLE HOCVIEN ADD CONSTRAINT UQ_MAHV UNIQUE (MAHV)
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_MAL_STT CHECK (LEFT (MAHV,3) LIKE MALOP)
ALTER TABLE HOCVIEN ADD SOTT CHAR(2)
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_STT CHECK(RIGHT (MAHV,2) LIKE SOTT)
--3.Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_GV_GT CHECK(GIOITINH IN('Nam','Nu'))
--4.Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_DIEM_FT CHECK(DIEM >= 0 AND DIEM <= 10)
--5.Kết quả thi là “Dat” nếu điểm từ 5 đến 10  và “Khong dat” nếu điểm nhỏ hơn 5.
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_KQT CHECK(KQUA IN('DAT','KHONG DAT'))
--6.Học viên thi một môn tối đa 3 lần.
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_LT_GH CHECK(LANTHI <= 3)
--7.Học kỳ chỉ có giá trị từ 1 đến 3.
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_HK_GH CHECK(HOCKY >= 1 AND HOCKY <= 3)
--8.Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”.
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_HV_GH CHECK(HOCVI IN('CN','KS','Ths','TS','PTS'))