USE QLGV

--9.Lớp trưởng của một lớp phải là học viên của lớp đó.
go
CREATE TRIGGER TRG01_INS_UPD_LOP ON LOP
FOR INSERT
AS
BEGIN
	IF EXISTS(SELECT *
			FROM INSERTED
			WHERE MALOP IN ( SELECT MALOP
							FROM HOCVIEN
							)
				AND TRGLOP NOT IN ( SELECT MAHV
									FROM HOCVIEN)
			)
	BEGIN
		PRINT 'ERROR: TRGLOP PHAI LA 1 HOCVIEN'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'NHAP/ UPDATE THANH CONG'
	END
END

