USE QLBH
--11.Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.
GO
CREATE TRIGGER TRG01_INS_HOADON ON HOADON
FOR INSERT
AS
BEGIN 
	DECLARE @MAKH CHAR(4);
	DECLARE @NGHD SMALLDATETIME;
	SELECT @MAKH = MAKH , @NGHD = NGHD FROM INSERTED
	DECLARE @NGDK SMALLDATETIME;
	SELECT @NGDK = NGDK 
	FROM KHACHHANG 
	WHERE MAKH = @MAKH 

	IF (@NGDK > @NGHD) 
	BEGIN 
		PRINT 'ERROR: NGDK phai  < NGHD'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN 
		PRINT 'HOA DON DA THEM THANH CONG'
	END
END


CREATE TRIGGER TR02_UPD_HOADON ON KHACHHANG
FOR UPDATE
AS
BEGIN 
	IF(SELECT COUNT(*) FROM HOADON K, INSETED I WHERE K.MAKH = I.MAKH  AND K.NGHD < I.NGDK ) > 0
	BEGIN 
		PRINT 'ERROR: NGDK phai  < NGHD'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'KHACH HANG DA UPDATE THANH CONG'
	END
END

CREATE TRIGGER TRG03_UPD_HOADON ON HOADON
FOR UPDATE
AS 
BEGIN
	IF(SELECT COUNT(*) FROM KHACHHANG K, INSERTED I WHERE K.NGDK > I.NGHD) > 0
	BEGIN
		PRINT 'ERROR: NGDK PHAI < NGHD'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'HOA DON DA UPDATE THANH CONG'
	END
END

--12.Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn.

CREATE TRIGGER TRG04_INS_HOADON ON HOADON
FOR INSERT
AS
BEGIN
	IF(SELECT COUNT(*) FROM CTHD K, INSERTED I WHERE I.SOHD = K.SOHD) < 1
	BEGIN
		PRINT 'ERROR: MOI HOA DON PHAI CO IT NHAT 1 CTHD'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'HOADON DA INSERT THANH CONG'
	END
END
GO
CREATE TRIGGER TRG05_DEL_CTHD ON CTHD
FOR UPDATE
AS
BEGIN
	IF(SELECT COUNT(*) FROM HOADON K, DELETED I WHERE K.SOHD = I.SOHD) < 1
	BEGIN
		PRINT 'ERROR: MOI HOA DON PHAI CO IT NHAT 1 CTHD'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'CTHD DA DUOC XOA THANH CONG'
	END
END

