USE QLBH

--LAM LAI CAU 18 THEO CACH 2
SELECT SOHD
FROM CTHD JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE NUOCSX = 'Singapore'
GROUP BY SOHD
HAVING COUNT(MASP) = (
	SELECT COUNT(MASP)
	FROM SANPHAM
	WHERE NUOCSX = 'Singapore'
)
--TIM KHACH HANG (MAKH) TUNG MUA TAT CA CAC SAN PHAM DO SINGAPORE SAN XUAT
SELECT MAKH
FROM HOADON INNER JOIN CTHD ON CTHD.SOHD = HOADON.SOHD INNER JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NUOCSX = 'Singapore'
GROUP BY MAKH
HAVING COUNT(DISTINCT SANPHAM.MASP) = (
	SELECT COUNT(MASP)
	FROM SANPHAM
	WHERE NUOCSX = 'Singapore'
)
--30.In ra danh sách các sản phẩm (MASP, TENSP) do “Trung Quoc” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của sản phẩm do “Trung Quoc” sản xuất).
SELECT * FROM SANPHAM
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA IN (
    SELECT TOP(3) GIA
    FROM SANPHAM
    WHERE NUOCSX = 'Trung Quoc'
    ORDER BY GIA DESC
)
--31.* In ra danh sách khách hàng nằm trong 3 hạng cao nhất (xếp hạng theo doanh số).
SELECT MAKH
FROM KHACHHANG
WHERE DOANHSO IN (
	SELECT TOP(3) DOANHSO
	FROM KHACHHANG
	ORDER BY DOANHSO DESC
	)
--43.*Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT MASP, TENSP
FROM SANPHAM JOIN (SELECT NUOCSX, MAX(GIA) GCN
	FROM SANPHAM
	GROUP BY NUOCSX) SP2 
	ON SP2.NUOCSX = SANPHAM.NUOCSX AND SANPHAM.GIA = SP2.GCN
--45.*Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT MAKH
FROM HOADON
WHERE MAKH IN(
SELECT TOP 10 MAKH
FROM KHACHHANG
ORDER BY DOANHSO DESC
)
GROUP BY MAKH
HAVING COUNT(SOHD) >= ALL(
	SELECT COUNT(SOHD)
	FROM HOADON
	WHERE MAKH IN(
		SELECT TOP 10 MAKH
		FROM KHACHHANG
		ORDER BY DOANHSO DESC
	)
	GROUP BY MAKH
)
--28
SELECT MASP, TENSP
FROM SANPHAM SP1
WHERE 2 >=(
	SELECT COUNT(DISTINCT GIA)
	FROM SANPHAM SP2
	WHERE SP2.GIA = SP1.GIA
)
--25
SELECT SOHD
FROM HOADON
WHERE YEAR(NGHD) = '2006'
AND TRIGIA >= ALL(
	SELECT TRIGIA
	FROM HOADON
	WHERE YEAR(NGHD) = '2006'
)
