USE QLBH

--12.Tìm các số hóa đơn đã mua sản phẩm có mã số “BB01” hoặc “BB02”, mỗi sản phẩm mua với số lượng từ 10 đến 20.
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB01' OR MASP = 'BB02' AND SL  BETWEEN 10 AND 20
--13.Tìm các số hóa đơn mua cùng lúc 2 sản phẩm có mã số “BB01” và “BB02”, mỗi sản phẩm mua với số lượng từ 10 đến 20.
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB01' AND SL  BETWEEN 10 AND 20
INTERSECT
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB02' AND SL BETWEEN 10 AND 20
--14.In ra danh sách các sản phẩm (MASP,TENSP) do “Trung Quoc” sản xuất hoặc các sản phẩm được bán ra trong ngày 1/1/2007.
SELECT DISTINCT SANPHAM.MASP, TENSP
FROM SANPHAM LEFT JOIN CTHD ON SANPHAM.MASP = CTHD.MASP JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE NUOCSX = 'Trung Quoc' OR NGHD = '1/1/2007'

SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
UNION
SELECT SANPHAM.MASP, TENSP
FROM SANPHAM JOIN CTHD ON CTHD.MASP = SANPHAM.MASP JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE NGHD = '1/1/2007'
--15.In ra danh sách các sản phẩm (MASP,TENSP) không bán được.
SELECT * FROM CTHD
SELECT DISTINCT SANPHAM.MASP, TENSP
FROM SANPHAM 
WHERE NOT EXISTS(
	SELECT*
	FROM CTHD
	WHERE SANPHAM.MASP = CTHD.MASP
	)
--Tim SOHD co muoc tri gia cao thu 3
SELECT SOHD
FROM HOADON HD1
WHERE 2 = (SELECT COUNT(DISTINCT TRIGIA)
FROM HOADON HD2
WHERE HD1.TRIGIA < HD2.TRIGIA)
--Tim SOHD co muc tri gia cao thu 4
SELECT SOHD
FROM HOADON HD1
WHERE 3 = (
	SELECT COUNT(DISTINCT TRIGIA)
	FROM HOADON HD2
	WHERE HD2.TRIGIA >HD1.TRIGIA
	)
--16.In ra danh sách các sản phẩm (MASP,TENSP) không bán được trong năm 2006.
SELECT * FROM CTHD
SELECT SANPHAM.MASP, TENSP
FROM SANPHAM
WHERE NOT EXISTS 
	(
		SELECT *
		FROM HOADON
		WHERE YEAR(NGHD) = '2006' AND NOT EXISTS 
		(
			SELECT *
			FROM CTHD
			WHERE SANPHAM.MASP = CTHD.MASP AND HOADON.SOHD = CTHD.SOHD
		)
	)
--17.In ra danh sách các sản phẩm (MASP,TENSP) do “Trung Quoc” sản xuất không bán được trong năm 2006.
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND NOT EXISTS
	(
		SELECT *
		FROM HOADON
		WHERE YEAR(NGHD) = '2006' AND NOT EXISTS
		(
			SELECT * 
			FROM CTHD
			WHERE SANPHAM.MASP = CTHD.MASP AND HOADON.SOHD = CTHD.SOHD
		)
	)
--18.Tìm số hóa đơn đã mua tất cả các sản phẩm do Singapore sản xuất.
SELECT SOHD
FROM HOADON
WHERE NOT EXISTS 
	(
		SELECT *
		FROM SANPHAM
		WHERE NUOCSX = 'Singapore' AND NOT EXISTS
		(
			SELECT *
			FROM CTHD
			WHERE HOADON.SOHD = CTHD.SOHD AND SANPHAM.MASP = CTHD.MASP
		)
	)