CREATE DATABASE QLBH
USE QLBH
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4),
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO MONEY,
	NGDK SMALLDATETIME
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4),
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME
)
CREATE TABLE SANPHAM
(
	MASP CHAR(4),
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
)
CREATE TABLE HOADON
(
	SOHD INT,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY
)
CREATE TABLE CTHD
(
	SOHD INT,
	MASP CHAR(4),
	SL INT
)
--1.	Tạo các quan hệ và khai báo các khóa chính, khóa ngoại của quan hệ.
ALTER TABLE KHACHHANG ALTER COLUMN MAKH CHAR(4) NOT NULL
ALTER TABLE KHACHHANG ADD CONSTRAINT PK_KH PRIMARY KEY (MAKH)

ALTER TABLE NHANVIEN ALTER COLUMN MANV CHAR(4) NOT NULL 
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_NV PRIMARY KEY (MANV)

ALTER TABLE SANPHAM ALTER COLUMN MASP CHAR(4) NOT NULL
ALTER TABLE SANPHAM ADD CONSTRAINT PK_SP PRIMARY KEY (MASP)

ALTER TABLE HOADON ALTER COLUMN SOHD INT NOT NULL
ALTER TABLE HOADON ADD CONSTRAINT PK_HD PRIMARY KEY (SOHD)
ALTER TABLE HOADON ADD CONSTRAINT FK_KH_HD FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON ADD CONSTRAINT FK_NV_HD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHD ADD CONSTRAINT FK_HD_CTHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTHD ADD CONSTRAINT FK_SP_CTHD FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
ALTER TABLE CTHD ALTER COLUMN SOHD INT NOT NULL
ALTER TABLE CTHD ALTER COLUMN MASP CHAR(4) NOT NULL
ALTER TABLE CTHD ADD CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)
--2.Thêm vào thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM.
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)
--3.Thêm vào thuộc tính LOAIKH có kiểu dữ liệu là tinyint cho quan hệ KHACHHANG.
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT
--4.Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100).
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)
--5.Xóa thuộc tính GHICHU trong quan hệ SANPHAM.
ALTER TABLE SANPHAM DROP COLUMN GHICHU
--6 NẾU MUỐN GIỞI HẠN GIẢ TRỊ NHẬP VÀO CỘT LOAIKH THÀNH:  “Vang lai”, “Thuong xuyen”, “Vip”, … THÌ CÓ THỂ SỬ DỤNG RÀNG BUỘC KIỂM TRA (CHECK CONSTRAINT) ĐỂ ĐẢM BẢO RẰNG CHỈ NHỮNG GIÁ TRỊ NÀY MỚI ĐƯỢC CHẤP NHẬN.
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_LOAIKH_VALIDVALUES CHECK (LOAIKH IN ('Vang lai', 'Thuong xuyen', 'Vip'))
--7.Đơn vị tính của sản phẩm chỉ có thể là (“cay”,”hop”,”cai”,”quyen”,”chuc”)
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_DVT_VALIDVALUES CHECK (DVT IN ('cay','hop','cai','quyen','chuc'))
--8.Giá bán của sản phẩm từ 500 đồng trở lên.
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_GIA_MINVALUES CHECK (GIA >= 500)
--9.Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm.
ALTER TABLE CTHD ADD CONSTRAINT CHECK_SL_MINVALUES CHECK (SL >= 1)
--10.Ngày khách hàng đăng ký là khách hàng thành viên phải lớn hơn ngày sinh của người đó.
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGDK_NGSINH CHECK (NGDK > NGSINH)